#pragma once

#define PARTICLE 0

#define PARTICLE_GRAVITY 0
#define PARTICLE_LINEAR 1

#define PARTICLE_STATE_LAUNCHED 1
#define PARTICLE_STATE_CREATED 0
#define PARTICLE_STATE_SPLASH 2
#define PARTICLE_STATE_END 3

#define PARTICLE_MANAGER_RAIN 0
#define PARTICLE_MANAGER_CRUMBLING 1
#define PARTICLE_MANAGER_EFFECT 2
