#define FILE_SEPARATOR "/"
#define FILE_FONT "."FILE_SEPARATOR"Polices"FILE_SEPARATOR"pkmndp.ttf"

#define ENTITEMAX 151 //Nombre d'entités TOTALES dans le jeu ENTIER

#define T_RED 190 //Transparence (couleur sous forme RVB)
#define T_GREEN 151
#define T_BLUE 255

#define TAILLEBLOC 48 //Taille d'un bloc dans le chipset du monde courant
#define TAILLEBLOCFENETRE 32 //Taille d'un bloc dans le chipset fenetre (morceau d'une fenetre)
#define TAILLEECRANMINX TAILLEBLOCFENETRE*15
#define TAILLEECRANMINY TAILLEBLOCFENETRE*13

#define NOSUCHFILE "."FILE_SEPARATOR"Sprites"FILE_SEPARATOR"nosuchfile.png"
#define COMBAT_COUNT 160

#define P_DEFINED 2 //Path défini
#define P_RANDOM 3//ou aléatoire
#define P_FIXED 1 //ou encore fixe

#define DOWN 0
#define RIGHT 1
#define UP 2
#define LEFT 3

#define BUTTON_CLOSE 0 //Type de boutons pouvant composer une fenêtre
#define BUTTON_TEXT_AREA 1
#define BUTTON_IMAGE_AREA 2
#define BUTTON_SCROLL_TEXT 3
#define BUTTON_INVENTORY_AREA 4
#define BUTTON_CHOICE 5
#define REFRESH_PNJWINDOW_COUNT 20

#define SKILL_PROJECTILE 0
#define SKILL_MELEE 1

#define SPRITEBANK_ANIMATION 0
#define SPRITEBANK_SKILL 1
#define SPRITEBANK_PHYSIC 2
#define SPRITEBANK_FACESET 3
#define SPRITEBANK_CHARSET 4
#define SPRITEBANK_PARTICLE 5
#define SPRITEBANK_NUMBER 6

#define SPRITEBANK_PATH_DIR "."FILE_SEPARATOR"Sprites"FILE_SEPARATOR
#define SPRITEBANK_PATH_ANIMATION SPRITEBANK_PATH_DIR"Animations"
#define SPRITEBANK_PATH_SKILL SPRITEBANK_PATH_DIR"Fight"
#define SPRITEBANK_PATH_PHYSIC SPRITEBANK_PATH_DIR"Physics"
#define SPRITEBANK_PATH_FACESET SPRITEBANK_PATH_DIR"Facesets"
#define SPRITEBANK_PATH_CHARSET SPRITEBANK_PATH_DIR"Charsets"
#define SPRITEBANK_PATH_PARTICLE SPRITEBANK_PATH_DIR"Particles"

#define SPRITE_ID_SHADOW 13

#define CHARACTER_ANIMATION_MOVE 0
#define CHARACTER_ANIMATION_ATTACK 1

#define STATS_TYPE_LINEAR 0
#define STATS_TYPE_SQUARE 1

#define STATS_HP 0
#define STATS_ATTACK 1
#define STATS_DEFENSE 2
#define STATS_SPE_ATTACK 3
#define STATS_SPE_DEFENSE 4
#define STATS_SPEED 5

#define AI_BALANCED 0
#define AI_OFFENSIVE 1
#define AI_DEFENSIVE 2

#define PARTICLE 0

#define PARTICLE_GRAVITY 0
#define PARTICLE_LINEAR 1

#define PARTICLE_STATE_LAUNCHED 1
#define PARTICLE_STATE_CREATED 0
#define PARTICLE_STATE_SPLASH 2
#define PARTICLE_STATE_END 3

#define PARTICLE_MANAGER_RAIN 0
#define PARTICLE_MANAGER_CRUMBLING 1
#define PARTICLE_MANAGER_EFFECT 2

#define EARTH_GRAVITY 9.81

#define BLOCK_ID_AIR INT16_MAX
#define BLOCK_ID_GRASS 363
#define BLOCK_ID_WATER_1 120
#define BLOCK_ID_WATER_2 121
#define BLOCK_ID_WATER_3 122

#define BLOCK_PROP_NONE 0
#define BLOCK_PROP_WATER 1
#define BLOCK_PROP_JUMPWALL 2
#define BLOCK_PROP_WIND_SENSITIVITY 3

#define BLOCK_COL_NO 0
#define BLOCK_COL_YES 1
#define BLOCK_COL_VOID 2

#define WIND_STOP 0
#define WIND_LEFT 1
#define WIND_RIGHT 2
#define WIND_NEUTRAL 3

//nombre de sprites différents dans la fiche d'un personnage sur une même ligne
#define HORIZONTAL_SPRITE_NUMBER_PER_CHAR_SHEET 6
//idem mais verticalement, sur une même colonne
#define VERTICAL_SPRITE_NUMBER_PER_CHAR_SHEET 8

#define WEATHER_ALPHA_LVL 100

#define SPAWN_LIMIT_ALLOWED 20

#define ID_CURRENT_POKEMON INT16_MAX-1
#define ID_CURRENT_OPPONENT INT16_MAX


#define EVENT_MOUSE 0
#define EVENT_KEYBOARD 1

#define POKEMON_TEAM_MAX_SIZE 6
